skin_analysis_main_configuration:  # 这里使用的阿里云的Access_key_id和Acess_key_secret
  access_key_id: 
  access_key_secret: 

img_to_oss:  # 我这里用的是阿里云OSS对象存储
  bucket_name: 
  oss_endpoint: 

skin_analysis:    # 这里是皮肤分析模型的一些参数
  access_key_id:
  access_key_secret: 
  org_id: "0001"
  org_name: "demo"
  endpoint: "imageprocess.cn-shanghai.aliyuncs.com"

deepseek_api:   # 这里需要使用DeepSeek的密钥，base_url和模型名称
  api_key:
  base_url:
  model_name:

gemma3n_api:    # 这里需要NIM上的密钥和base_url，还有模型名称和基本参数
  api_key: 
  invoke_url:
  model_name:
  max_tokens: 

front_end_configuration:    # 这里是前端的设计
  custom_css_path: assets/custom_css.css
  intro_section_path: assets/intro_section.html
  benefit_section_path: assets/benefit_section.html


  

